//产品详情
export const GET_PRODUCTDETAIL_BEGIN = 'GET_PRODUCTDETAIL_BEGIN'
export const GET_PRODUCTDETAIL_SUCCESS = 'GET_PRODUCTDETAIL_SUCCESS'
export const GET_PRODUCTDETAIL_FAIL = 'GET_PRODUCTDETAIL_FAIL'

//用户登录
export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
//app同步登录态
export const SSO_BEGIN = 'SSO_BEGIN'
export const SSO_SUCCESS = 'SSO_SUCCESS'
export const SSO_FAIL = 'SSO_FAIL'
export const LOGIN_RESET = 'LOGIN_RESET'

//是否有账户

//升级跳转信息
export const  GET_UPDATREINFO_BEGIN = 'GET_UPDATREINFO_BEGIN'
export const  GET_UPDATREINFO_SUCCESS = 'GET_UPDATREINFO_SUCCESS'
export const  GET_UPDATREINFO_FAIL = 'GET_UPDATREINFO_FAIL'
export const  RESET_UPDATREINFO = 'RESET_UPDATREINFO'

//用户信息回显
export const GET_ACCOUNT_INFO_BEGIN = 'GET_ACCOUNT_INFO_BEGIN'
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS'
export const GET_ACCOUNT_INFO_FAIL = 'GET_ACCOUNT_INFO_FAIL'
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO'

//保单提交
//order
export const CREATE_ORDER_BEGIN = 'CREATE_ORDER_BEGIN'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const RESET_ORDER = 'RESET_ORDER'

//退保保费计算
export const SURRENDER_CHARGE_BEGIN = 'SURRENDER_CHARGE_BEGIN'
export const SURRENDER_CHARGE_SUCCESS = 'SURRENDER_CHARGE_SUCCESS'
export const SURRENDER_CHARGE_FAIL = 'SURRENDER_CHARGE_FAIL'

//退保
export const SURRENDER_BEGIN = 'SURRENDER_BEGIN'
export const SURRENDER_SUCCESS = 'SURRENDER_SUCCESS'
export const SURRENDER_FAIL = 'SURRENDER_FAIL'
export const RESET_SURRENDER = 'RESET_SURRENDER'
